package edu.arizona.wood.tom.Model;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

@DynamoDBTable(tableName = "Questions")
public class Question {
	private String qid;
	private String question;
	private String imgUrl;
	private String correctResponse;
	private String response1;
	private String response2;
	private String response3;
	private String questionRating;
	private String createdBy;
	private String locationCreated;
	private String dateCreated;
	

	@DynamoDBHashKey(attributeName = "qid")
    @DynamoDBAutoGeneratedKey
	public String getQid() {
		return qid;
	}
	public void setQid(String qid) {
		this.qid = qid;
	}
	
	@DynamoDBAttribute(attributeName = "question")
	public String getQuestion() {
		return question;
	}
	public void setQuestion(String question) {
		this.question = question;
	}
	
	@DynamoDBAttribute(attributeName = "imgurl")
	public String getImgUrl() {
		return imgUrl;
	}
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}
	
	@DynamoDBAttribute(attributeName = "cresponse")
	public String getCorrectResponse() {
		return correctResponse;
	}
	public void setCorrectResponse(String correctResponse) {
		this.correctResponse = correctResponse;
	}
	
	@DynamoDBAttribute(attributeName = "response1")
	public String getResponse1() {
		return response1;
	}
	public void setResponse1(String response1) {
		this.response1 = response1;
	}
	
	@DynamoDBAttribute(attributeName = "response2")
	public String getResponse2() {
		return response2;
	}
	public void setResponse2(String response2) {
		this.response2 = response2;
	}
	
	@DynamoDBAttribute(attributeName = "response3")
	public String getResponse3() {
		return response3;
	}
	public void setResponse3(String response3) {
		this.response3 = response3;
	}
	
	@DynamoDBAttribute(attributeName = "rating")
	public String getQuestionRating() {
		return questionRating;
	}
	public void setQuestionRating(String questionRating) {
		this.questionRating = questionRating;
	}
	
	@DynamoDBAttribute(attributeName = "createdby")
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	
	@DynamoDBAttribute(attributeName = "locationcreated")
	public String getLocationCreated() {
		return locationCreated;
	}
	public void setLocationCreated(String locationCreated) {
		this.locationCreated = locationCreated;
	}
	
	@DynamoDBAttribute(attributeName = "datecreated")
	public String getDateCreated() {
		return dateCreated;
	}
	public void setDateCreated(String dateCreated) {
		this.dateCreated = dateCreated;
	}
}